### ISSUE TITLE
the final project of Yunxuan Chen 

### ISSUE THREAD

**Issue by yunxuan0724** [QMSS-G5072-2020/final_project_yunxuan_chen#1]
SHA: 19785e2
@tbrambor @SUN-Wenjun @lonadai0121 @QMSS-G5072-2020/teaching_team

**Comment by lonadai0121** [comment]
3/5 Satisfactory Project: lack of complexity. The chosen task was acceptable, but fairly conservative in ambition.
3/3 well commented and documented
2/3 The code is correct, but could be edited down to leaner code. 
1/3  Basic recommendations for how a Python package should be structured were ignored.
1/3 Documentation of the package and its contents is largely absent.
3/3 The package installs without problems.
1/3  Testing for the package is absent.

Late: submitted on 12/24 (due date: by 9am on 12/19)
